### ISSUE TITLE
Message IDs

### ISSUE THREAD

**Issue by yuzuhaqi** [Jodenee/Discohook#1]
Not really an issue, just can't see a "suggestions" tab. But is there any possible way when you use :execute() to be able to get the message id it sent?

**Comment by Jodenee** [comment]
Yes! If you set the `waitForMessage` arg to true a [Message](https://github.com/Jodenee/Discohook/blob/main/docs/Message.md) or [ThreadMessage](https://github.com/Jodenee/Discohook/blob/main/docs/ThreadMessage.md) object will be returned depending on where the message was sent.

Here's a quick example: 
```lua
local webhook = require(path_to_module).new("webhookId", "webhookToken")
local message = webhook:execute("Hello!", nil, false, true)

print("MessageId: ", message.id)
```

I hope this answered your question!

**Comment by yuzuhaqi** [comment]
Thank you so much! You should definitely put this onto the documentation or whatever.
